//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zahard_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost
    {
        public int taxes { get; set; }
        public int maintenance { get; set; }
        public int electricity { get; set; }
        public int others { get; set; }
        public Nullable<System.DateTime> months { get; set; }
    }
}
