//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zahard_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class oreder_custm
    {
        public int CLient_id { get; set; }
        public string Client_name { get; set; }
        public string Email { get; set; }
        public int Car_id { get; set; }
        public string Car_name { get; set; }
        public int Model { get; set; }
        public int Order_id { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public int price { get; set; }
    }
}
